### ISSUE TITLE
Exception PUBSUB breaks.

### ISSUE THREAD

**Issue by PedroMPagani** [InvisRaidinq/redstone#1]
If any exception happens, the pubsub should be be breaking, on the .subscribe, also, it is usually recommended that a Jedis connection is kept as private and not used from the Pools for when subscribing, could change that too.

If you want to reduce and avoid PING methods, you might also want to use the retryable executor instead of just the .publish, which will call a .ping() first on .getResource() and them will bring it in, this avoids RTT cost :)

**Comment by InvisRaidinq** [comment]
Hey, thanks for letting me know - you're welcome to open up a PR if you want to make the changes, or I can potentially look into it when I get more time. 

I wasn't actually aware a retryable executor existed for the event a publish fails!

**Comment by InvisRaidinq** [comment]
Closing due to lack of response / additional PR.
