### ISSUE TITLE
PUB/SUB for data handling?

### ISSUE THREAD

**Issue by pedroagrs** [InvisRaidinq/redstone#2]
# Why not use the redis client with pipeline? 
PUB/SUB is used for messaging and is insecure for data handling because redis doesn't return a status code when a message is received _(maybe migrate to rabbitmq?)_.

**Articles:**
[Redis pipeling](https://redis.io/docs/manual/pipelining/)
[Redis pub/sub](https://redis.io/docs/interact/pubsub/)

 ### Some reasons:
- Internally the pipeline is queued/ordered FIFO based;
- Redis does not guarantee ordered delivery. It simply pushes available messages to consumers; (Jason Ngan's article)
- If a consumer restarts after a shutdown, there’s no way it can know if there are any missed messages. (Jason Ngan's article)

### Some solutions:
- Create an internally callback for data listeners;
- Print pub/sub's stacktrace and do not suppress it.

**Anyway, let me know if you have any feedback on this issue! Feel free to send me your opinion.**

**Comment by InvisRaidinq** [comment]
Although what you're saying is technically correct, it goes way past the specification of this project. The purpose of it was to create a super simple redis pub/sub implementation that I could quickly throw into a project of mine. 

Given the nature of what it was going to be used for, I wasn't too worried about missed messages, hence no callback required (which is also beneficial in terms of overall performance, as it doesn't have to send a confirmation message back to the handler).

It's also supposed to be redis-based - the scope of the project was that it was to use redis, hence it uses redis. Although RabbitMQ would technically be a better option, reds is used much more commonly on smaller scales (from what I've experienced), hence was the elected option.

Essentially, you've opened an issue for something that's way out of the scope of this incredibly small project. You're more than welcome to create a pull request with these changes if you'd like to see them / use them yourself, but it's not something that's planned.
